#/bin/bash

costshare_chase_vendor_pct_tbl(){
cat <<'vendor_pct_tbl'
Vendor Name                     ,Pct Owed By Party 'X' 
BJS FUEL			,50
110 GRILL			,29
EVVIVA TRATTORIA		,29
GRABULL INC			,29
RED GINGER			,29
GIGI'S RESTAURANT		,29
EL HUIPIL MEXICAN		,29
SMACK NOODLE			,29
OKI POKE			,29
LOBSTER COVE			,29
KARMA WESTFORD			,29
TST* FIREFLY S BBQ		,29
TST* NAN S RUSTIC KITCHEN	,29
CHEESECAKE NATICK		,29
BUENO Y SANO			,29
KINDLES PI*			,29
ATLANTIC SEA GRILL		,29
COLONIAL SPIRITS		,29
EMMAS CAFE			,29
WOODMANS OF ESSEX		,29
SQ *ERIKSONS DAIRY		,29
T.C. LANDO'S SUB'S		,29
BROTHERS MARKETPLACE		,29
IDYLWILDE FARMS INC		,29
KENNEDYS MARKET			,29
MARKET BASKET			,29
PAYPAL *DEPALOCOFFE		,29
PRICE CHOPPER			,29
ROCHE BROTHERS			,29
SHAWS OSCO			,29
SQ *SMALL FARM  INC		,29
STOP &amp; SHOP			,29
TWIN SEAFOOD			,29
WHOLEFDS WSF			,29
WHOLEFDS SBY			,29
TST* ATLANTIC POKE		,29
HONEY POT HILL ORCHARD		,29
HELENS RESTAURANT		,29
vendor_pct_tbl
}

